Feature password accordion
Onlineberatung/onlineBeratung-frontend pull request #141
Opened 2021-03-22 13:47 UTC by iam-robin

## Proposed Changes

  - add password input logic into form accordion
  - add password criteria validation
  - add new styles for data protection checkbox
  - clean up registration component

2021-03-23 15:14 UTC, koepferd requested changes

2021-03-23 15:14 UTC, koepferd commented on src/components/registration/Registration.tsx
>  										'registration.required.infoText'
Is there a reason why you only moved a part of the submit section up to the accordion?
Please move comment and infoText up to the submit button.

2021-03-23 15:14 UTC, koepferd commented on src/components/registration/RegistrationPassword.tsx
> +
please remove empty line

2021-03-23 15:14 UTC, koepferd commented on src/components/registration/RegistrationPassword.tsx
> +				<li
You can use an array here to render these list items with their related texts and validation.

2021-03-23 15:18 UTC, koepferd commented on src/components/registration/Registration.tsx
>  								{consultingType === 1 && (
This special logic for ct 1 needs to be added to the password component in the accordion

2021-03-23 15:35 UTC, iam-robin commented on src/components/registration/Registration.tsx
>  										'registration.required.infoText'
clean up of the mandatory info text and * will be done in the voluntary-info-story of the current sprint

2021-03-24 14:24 UTC, koepferd approved these changes

2021-03-25 10:49 UTC, merged