Feature voluntary registration info
Onlineberatung/onlineBeratung-frontend pull request #151
Opened 2021-04-06 06:51 UTC by iam-robin

## Proposed Changes

  - add new registration accordion steps (age, state) for u25/gse
  - move voluntary infos from registration to further steps (inside the app)
  - add new voluntary info call

2021-04-06 07:28 UTC, koepferd requested changes

2021-04-06 07:28 UTC, koepferd commented on src/resources/scripts/i18n/de/furtherStepsInformal.ts
> +		'Dabei hilft es uns, wenn Du weitere freiwillige Angaben zu Dir und Deinen Anliegen machst.'
Small typo: *Deinem

2021-04-06 10:20 UTC, koepferd approved these changes, later dismissed

2021-04-08 12:48 UTC, koepferd submitted a review, later dismissed

2021-04-09 12:43 UTC, koepferd requested changes

2021-04-09 12:43 UTC, koepferd commented on src/components/headline/Headline.tsx
> +			className={`headline headline--${levelBasedClass}${
please add space again otherwise any optional classname will break the style

2021-04-09 12:46 UTC, iam-robin commented on src/components/headline/Headline.tsx
> +			className={`headline headline--${levelBasedClass}${
you're right. Fixed it 👍

2021-04-09 12:47 UTC, koepferd approved these changes

2021-04-09 12:58 UTC, merged