Refactor: Use consulting type servie
Onlineberatung/onlineBeratung-frontend pull request #175
Opened 2021-05-06 13:59 UTC by amannn

WIP

2021-05-07 11:33 UTC, amannn commented on src/components/formAccordion/FormAccordion.tsx
> +						options: stateData
I was thinking we could potentially move the state options to the API as well. It's not necessary for the Diakonie and Caritas, but maybe something for our backlog?

2021-05-07 11:33 UTC, amannn commented on src/components/registration/registrationHelpers.ts
> +		label: translate('registration.state.options.1')
I've used a more specific translation identifier here now, since these are not only used for U25, but for all consulting types that render the state dropdown. This was already the case before.

2021-05-07 11:33 UTC, amannn commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	};
A bit stricter typing to catch errors easier.

2021-05-07 11:33 UTC, amannn commented on cypress/integration/registration.spec.ts
> +		beforeEach(() => {
I've removed most consulting types from this file and picked addiction and U25 as representative examples to test. Since we're using API data now we'd mostly test the provided mock data otherwise.

Does that make sense to you?

2021-05-11 07:33 UTC, koepferd requested changes

2021-05-11 07:33 UTC, koepferd commented on src/resources/scripts/i18n/de/registration.ts
> +	'state.dropdown': 'Bundesland auswählen*',
The state translations are already implemented in `userU25.ts`.
Please remove them there and make sure the translations aren't used anymore (e.g. monitoring).

2021-05-11 07:33 UTC, koepferd commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	urls: {
Please check, I think the urls and registration notes are optional.

2021-05-11 07:33 UTC, koepferd commented on src/components/formAccordion/FormAccordion.tsx
> +						options: stateData
Yes, please add this to our backlog :-)

2021-05-11 07:33 UTC, koepferd commented on src/components/registration/WelcomeScreen.tsx
> +			<h2>{props.title}</h2>
Please use the `<Headline />` component

2021-05-11 07:33 UTC, koepferd commented on src/resources/scripts/i18n/de/registration.ts
>  	'title.start': 'Registrierung',
Are both of these texts still used?

2021-05-11 07:33 UTC, koepferd commented on src/components/registration/WelcomeScreen.tsx
> +			<h2>{props.title}</h2>
Did we make sure that the welcome title from the api contains the whole title?

2021-05-11 07:33 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"welcome": "Willkommen bei der Suchtberatung",
There is a "!" missing here.

2021-05-11 07:33 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"welcome": "Willkommen bei der Suchtberatung",
Please check addiction and u25 mock data.
I'd like them to be real for these to consultingTypes so we avoid wrong tests.
E.g. user roles, required/voluntary components, sessionDataInitializing,....

2021-05-11 07:33 UTC, koepferd commented on src/components/app/LoginLoader.tsx
> +const CONSULTING_TYPE_SLUG_PATTERN = /^[\w\d-]+$/;
nice!

2021-05-11 07:33 UTC, koepferd commented on cypress/integration/registration.spec.ts
> +		beforeEach(() => {
Yes, that makes sense.
But I'd like to check all special cases at least once.

E.g. `emigration` has `registration-agency-selection-note`. If you could add another mock and test this it'd be great.

2021-05-11 11:29 UTC, amannn commented on src/resources/scripts/i18n/de/registration.ts
> +	'state.dropdown': 'Bundesland auswählen*',
Is it ok for you if I remove the user25 and userAddiction labels in the next PR where I focus on removing these hardcoded references? It's a bit more effort and maybe this PR could focus more on generally working with the consulting type service.

I have a feeling that these changes will be somewhat integrated anyway.

What do you think?

2021-05-11 11:51 UTC, amannn commented on src/components/registration/WelcomeScreen.tsx
> +			<h2>{props.title}</h2>
> Did we make sure that the welcome title from the api contains the whole title?

We have to make sure we provide it this way when the data is set up. Currently no real data exists. But we intend to do it this way, right? The idea was that we're more flexible and don't have to assemble something, where some parts of the label come from the UI and some from the data.

2021-05-11 11:56 UTC, amannn commented on src/resources/scripts/i18n/de/registration.ts
>  	'title.start': 'Registrierung',
Yep, in `RegistrationForm` and `Registration`.

2021-05-11 12:39 UTC, amannn commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"welcome": "Willkommen bei der Suchtberatung",
Good point!

2021-05-11 13:47 UTC, amannn commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	urls: {
I just confirmed with @daho4b: Objects within a consulting type will always be present, regardless of if nested properties are actually set. Individual properties can be `null` of course and also absent. So there could even be an empty `urls` object with no properties, but we can rely on that the `urls` object is present.

2021-05-19 07:55 UTC, amannn commented on src/resources/scripts/i18n/de/registration.ts
> +	'state.dropdown': 'Bundesland auswählen*',
As discussed the other day we'll leave this for now.

2021-05-19 07:56 UTC, amannn commented on cypress/integration/registration.spec.ts
> +		beforeEach(() => {
`emigration` is added now 👍

2021-05-21 09:12 UTC, koepferd commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	urls: {
Thanks for clarifying 🙂

2021-05-21 09:14 UTC, koepferd commented on src/components/registration/WelcomeScreen.tsx
> +			<h2>{props.title}</h2>
Yes, I'll take this with me to handle in the other project scope

2021-05-21 09:54 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"groupChatRules": [
ct 0 has no groupChatRules

2021-05-21 11:15 UTC, koepferd requested changes

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"sendWelcomeMessage": true,
ct 0 has no welcomeMessage

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"state": true
ct 0 has no state

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +	"showAskerProfile": false,
ct 0 should have showAskerProfile: true

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.emigration.json
> +		"autoSelectAgency": false,
ct 17 has autoSelectAgency: true

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.emigration.json
> +		"whiteSpotAgencyId": 100
ct 17 has whiteSpotAgencyId: 1731

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +		"registrationDropdown": "Sucht-Selbsthilfe - Kreuzbund"
Should be "Suchtberatung"

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +		"registrationDropdown": "Beratung für Suizidgefährdete junge Menschen [U25]"
Can be empty as this ct is "isSubsequentRegistrationAllowed" false.

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +		"autoSelectAgency": false,
should be `true`

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +			"age": false,
should both be `true`

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +		"whiteSpotAgencyAssigned": true,
should `false` and whiteSpotAgencyId  `null`

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +	"sendFurtherStepsMessage": true,
should be `false`

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +	"sessionDataInitializing": {
age, gender, state should be `true`

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +		"initializeMonitoring": false
should be `true`
plus add: `"monitoringTemplateFile": "u25.json"` in monitoring object

2021-05-21 11:15 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.u25.json
> +	"initializeFeedbackChat": false,
should be `true`

2021-05-21 11:44 UTC, amannn commented on cypress/fixtures/service.consultingtypes.u25.json
> +		"registrationDropdown": "Beratung für Suizidgefährdete junge Menschen [U25]"
Didn't we want to leave this and get rid of the condition?

2021-05-21 14:52 UTC, koepferd approved these changes

2021-05-25 07:39 UTC, merged