Refactor: Remove static consulting type usage
Onlineberatung/onlineBeratung-frontend pull request #176
Opened 2021-05-07 12:26 UTC by amannn

WIP

**TODO:**
- [ ] Wait for parent branch to be merged and change target to develop

2021-05-17 11:29 UTC, amannn commented on .github/workflows/build.yml
> +                  path: cypress/videos/
I had some issues with failing Cypress tests at some point. This can be helpful to debug the issue.

2021-05-17 11:30 UTC, amannn commented on cypress/fixtures/service.users.data.askers.json
> -		"19": { "sessionData": null, "isRegistered": false, "agency": null }
Most of these don't exist in our consulting type mocks.

2021-05-17 11:35 UTC, amannn commented on cypress/integration/tokens.spec.ts
> +	beforeEach(() => {
Interestingly this was necessary to get the tests to pass. I don't know why that would make a difference but now tests work consistently.

2021-05-17 11:41 UTC, amannn commented on src/components/app/AuthenticatedApp.tsx
> +			Promise.all([apiGetUserData(), apiGetConsultingTypes()])
This is an important change. Since we need to access consulting type data in quite a few places in the authenticated part of the app, I thought it might be a good idea to fetch them all at first and therefore being able to use them synchronously afterwards.

Alternatively we'd have much more asynchronicity along with loading and error states spread across components and would have to find a solution with caching.

2021-05-17 11:42 UTC, amannn commented on src/components/askerInfo/AskerInfoData.tsx
> +	getAddictiveDrugsString
As discussed we'll leave this for the time being.

2021-05-17 11:44 UTC, amannn commented on src/components/askerInfo/AskerInfoData.tsx
> +	);
This hook makes it convenient to read a single consulting type during render.

2021-05-17 11:46 UTC, amannn commented on src/components/profile/AskerAboutMeData.tsx
> +	const showEmail = hasAskerEmailFeatures(userData, consultingTypes);
Was able to turn this into a synchronous call now that we have consulting types generally available.

2021-05-17 11:50 UTC, amannn commented on src/components/profile/profileHelpers.ts
> +					  )?.isSubsequentRegistrationAllowed &&
The flag here is inverted, hence the negation is gone.

2021-05-17 11:52 UTC, amannn commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	voluntaryComponents?: any[];
Split into two types now. The upper one is the one coming from the list endpoint, the other one from the detail endpoint.

2021-05-17 11:53 UTC, amannn commented on src/components/sessionHeader/SessionHeaderComponent.tsx
> +						!consultingType.showAskerProfile
Here we have to negate the flag, right? Below there's the same story.

2021-05-17 11:55 UTC, amannn commented on src/components/profile/AskerRegistration.tsx
> -					) {
Not sure why the condition was necessary here? It's just the opposite of the condition in `if`, right?

2021-05-17 11:59 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> -				props.selectedConsultingType !== 0),
I didn't fully understand this condition here. Should there be special behaviour for the consulting type with the ID `0`?

2021-05-18 09:06 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +							props.consultingType.id
Should this be:

```suggestion
							props.consultingType.id != null
```

? Or are we purposefully omitting the consulting type `0` here? That would mean we have hardcoded access to it though.

2021-05-18 09:15 UTC, amannn commented on src/components/profile/AskerRegistration.tsx
> +		selectedConsultingTypeId && selectedAgency;
Should this be:

```suggestion
		selectedConsultingTypeId != null && selectedAgency;
```

? Or is there special behaviour for the consulting type `0`?

2021-05-21 15:51 UTC, koepferd requested changes

2021-05-21 15:51 UTC, koepferd commented on src/components/profile/profileHelpers.ts
> +			label: consultingType.groupChat.isGroupChat
Let's refactor this as discussed. The title.registrationDropdown will be required in the consultingType Data and can always be used here.

2021-05-21 15:51 UTC, koepferd commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	voluntaryComponents?: any[];
Instead of adding a new interface I'd suggest to implement the interface via `dtsgen`. Though I think we might need until the consultingTypeService is available for open source.

2021-05-21 15:51 UTC, koepferd commented on src/globalState/state.tsx
> +import { ConsultingTypesProvider } from './provider/ConsultingTypesProvider';
Please import from the `index.ts` to stay consistent here.

2021-05-21 15:51 UTC, koepferd commented on cypress/fixtures/service.users.data.askers.json
> -		"19": { "sessionData": null, "isRegistered": false, "agency": null }
Okay but please keep ct `0` and `17` as we have mocked data for these cts.

2021-05-21 15:51 UTC, koepferd commented on cypress/integration/tokens.spec.ts
> +	beforeEach(() => {
Hm, I don't know either why that should make a difference.

2021-05-21 15:51 UTC, koepferd commented on src/components/sessionHeader/SessionHeaderComponent.tsx
> +						!consultingType.showAskerProfile
Correct 👌🏻

2021-05-21 15:51 UTC, koepferd commented on src/components/sessionHeader/SessionHeaderComponent.tsx
> +						!consultingType.showAskerProfile
As I tested this: useConsultingType does not include showAskerProfile.

2021-05-21 15:51 UTC, koepferd commented on src/components/agencySelection/AgencySelection.tsx
> +	const showPreselectedAgency = preselectedAgency && autoSelectPostcode;
This might cause the bug I told you about:
`const showPreselectedAgency = preselectedAgency && !autoSelectPostcode;`

The agency should be shown when the postcode is not autoselected.

2021-05-21 15:51 UTC, koepferd commented on src/components/agencySelection/AgencySelection.tsx
> -				props.selectedConsultingType !== 0),
Hm, I think this might actually an error. 

Anyway it's deprecated as by now the input field is only displayed when you already selected a consulting type and `autoSelectPostcode` is disabled -> please remove the disabled property here.

2021-05-21 15:51 UTC, koepferd commented on src/components/profile/AskerRegistration.tsx
> +		selectedConsultingTypeId && selectedAgency;
Nope, you are correct, please commit this change!

2021-05-21 15:51 UTC, koepferd commented on src/components/agencySelection/AgencySelection.tsx
> +	}, [props.preselectedAgency]);
This useEffect should also reset when `props. consultingType` changes.

2021-05-21 15:51 UTC, koepferd commented on src/components/agencySelection/AgencySelection.tsx
> +							props.consultingType.id
Yes, please commit your suggestion :-)

2021-05-21 15:53 UTC, koepferd commented on src/components/sessionHeader/SessionHeaderComponent.tsx
> +						!consultingType.showAskerProfile
Please check and if needed suggest a change to the api here.

2021-05-25 07:49 UTC, amannn commented on src/globalState/interfaces/ConsultingTypeInterface.ts
> +	voluntaryComponents?: any[];
As discussed last week, I made a note in DOB-83 to take care of this once the consulting type service is open sourced and available for the Caritas.

2021-05-25 08:13 UTC, amannn commented on src/components/profile/profileHelpers.ts
> +			label: consultingType.groupChat.isGroupChat
I've removed the condition to always use `registrationDropdown` and added a note in DOB-10 so we consider this when setting up the consulting types.

2021-05-25 08:42 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +	const showPreselectedAgency = preselectedAgency && autoSelectPostcode;
Well spotted, thanks!

2021-05-25 08:55 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +	const showPreselectedAgency = preselectedAgency && autoSelectPostcode;
It seems like the bug we discussed was caused by another wrong condition though. I've got it fixed now.

2021-05-25 14:39 UTC, amannn commented on src/components/sessionHeader/SessionHeaderComponent.tsx
> +						!consultingType.showAskerProfile
This is now available in `docker.pkg.github.com/virtualidentityag/diakonie-onlineberatung-consultingtypeservice/diakonie-onlineberatung-consultingtypeservice:dockerimage.v.5.feat-extension-of-basic-response-with-show-asker-profile`.

2021-06-02 08:06 UTC, koepferd approved these changes

2021-06-02 08:07 UTC, koepferd commented
Open Todo:

- [ ] await testing with configured consulting types

2021-06-02 09:08 UTC, merged