Feature register other resorts in user profile
Onlineberatung/onlineBeratung-frontend pull request #19
Opened 2020-07-21 09:43 UTC by koepferd

Part of #14 

## Proposed Changes

  - added component in user profile to register to other resorts with the same account
  - added new registration call, error handling and redirect to writing a new enquiry
  - refactored basic registration call & enquiry logic

2020-07-21 11:45 UTC, iam-robin commented on src/components/profile/ts/AskerNewRegistration.tsx
> +	const isAllRequiredDataSet = () =>
Does it make sense for clarity reasons to define the constant above the UseEffect functions? Especially since the constant is not only used in the following UseEffect, but also in an other function.

2020-07-21 11:45 UTC, iam-robin commented on src/resources/ts/i18n/de/profile.ts
> +		'Es ist ein Fehler aufgetreten.Bitte versuchen Sie es erneut.',
Missing space after the full stop.

2020-07-21 11:45 UTC, iam-robin commented on src/resources/ts/i18n/de/profile.ts
> +	'data.registerError.overlay.buttonLabel': 'Schliessen',
Is 'schließen' intentionally written here with two s instead of a ß?

2020-07-21 11:45 UTC, iam-robin commented on src/resources/ts/i18n/de/profileInformal.ts
> +		'Es ist ein Fehler aufgetreten.Bitte versuche es erneut.'
Also a missing space after the full stop.

2020-07-21 12:46 UTC, koepferd commented on src/components/profile/ts/AskerNewRegistration.tsx
> +	const isAllRequiredDataSet = () =>
yes, you are right, thanks!

2020-07-21 15:16 UTC, koepferd commented on src/resources/ts/i18n/de/profile.ts
> +	'data.registerError.overlay.buttonLabel': 'Schliessen',
yes, this is a deliberate design decision since all button labels are uppercase and ß has no uppercase version.

2020-07-23 13:00 UTC, iam-robin commented on src/components/enquiry/ts/WriteEnquiry.tsx
> +			!activeSessionGroupId
does it make sense to remove the negation (!) and switch the if/else cases for readability reasons?

2020-07-23 13:28 UTC, koepferd commented on src/components/enquiry/ts/WriteEnquiry.tsx
> +			!activeSessionGroupId
Absolutely, thanks. Will do the same in line 55++.

2020-07-24 08:55 UTC, iam-robin approved these changes

2020-07-24 08:56 UTC, iam-robin commented on src/components/enquiry/ts/WriteEnquiry.tsx
>  			!activeSessionGroupId
you've changed the if/else order but you haven't adjusted the condition. Or do I miss something?

2020-07-24 08:57 UTC, iam-robin reviewed
[deleted]

2020-07-24 08:58 UTC, iam-robin requested changes
see comment above

2020-07-24 09:04 UTC, koepferd commented on src/components/enquiry/ts/WriteEnquiry.tsx
>  			!activeSessionGroupId
... I fixed it

2020-07-24 10:09 UTC, iam-robin approved these changes

2020-07-29 09:42 UTC, merged