feat: provide config for button
Onlineberatung/onlineBeratung-frontend pull request #193
Opened 2021-05-26 09:31 UTC by amannn

WIP

2021-05-27 14:31 UTC, amannn commented on src/components/app/authenticatedApp.styles.scss
> +		background-color: $background-light;
I've renamed this to something more generic that doesn't imply a specific color value.

2021-05-27 14:32 UTC, amannn commented on src/components/app/navigation.styles.scss
> -		fill-opacity: 0.7;
The opacity for the title and icon in the navigation was generally a bit finetuned.

2021-05-27 14:32 UTC, amannn commented on src/components/app/navigation.styles.scss
> +		letter-spacing: 0.5px;
For better readability.

2021-05-27 14:33 UTC, amannn commented on src/components/button/button.styles.scss
> +		border-radius: $button-border-radius;
I've added a few variables here for theming.

2021-05-27 14:33 UTC, amannn commented on src/components/button/button.styles.scss
> +			text-decoration: underline;
This affects the Caritas too. I hope it's ok as a general improvement. Otherwise we can of course add another variable.

2021-05-27 14:34 UTC, amannn commented on src/components/button/button.styles.scss
> +		}
I've added a hover state for the generic "small icon" button – the other ones keep their existing hover state. The scroll to bottom button in the session view is the only call site for this variant.

2021-05-27 14:35 UTC, amannn commented on src/components/formAccordion/formAccordionItem.styles.scss
> +		}
Improvements for Diakonie. Caritas still looks the same.

2021-05-27 14:36 UTC, amannn commented on src/components/login/login.styles.scss
> +			padding: 0 150px;
Some style improvements for the Diakonie here as well which don't affect the look of Caritas.

2021-05-27 14:36 UTC, amannn commented on src/components/message/message.styles.scss
> +			background-color: $message-background;
This variable is more generic now as well to not imply a specific color value.

2021-05-27 14:37 UTC, amannn commented on src/components/monitoring/monitoring.styles.scss
> +					background-color: rgba($primary, 0.05);
Removed the hardcoded color value in favour of variable usage.

2021-05-27 14:38 UTC, amannn commented on src/components/overlay/Overlay.tsx
> +	className?: string;
I'm a bit unsure what goes on the `item` part and what on `props` directly. What is the pattern here?

2021-05-27 14:39 UTC, amannn commented on src/components/profile/DeleteAccount.tsx
> +		className: 'deleteAccount__overlay',
I think there was a bug here previously:

![Screenshot 2021-05-26 at 14 40 28](https://user-images.githubusercontent.com/4038316/119845943-fde22800-bf09-11eb-9255-e9dd68c2d67b.png)

The delete account styles moved the text to be left-aligned, however this didn't affect just the delete account overlay, but all overlays.

![Screenshot 2021-05-26 at 14 40 34](https://user-images.githubusercontent.com/4038316/119846062-18b49c80-bf0a-11eb-9e28-e3753eb13d74.png)


I've now scoped the styles to this component.

2021-05-27 14:40 UTC, amannn commented on src/components/registration/registration.styles.scss
> +			max-width: 1000px;
An improvement that is helpful for the Diakonie but, again, doesn't affect the Caritas.

2021-05-27 14:41 UTC, amannn commented on src/components/select/SelectDropdown.tsx
> +			backgroundColor: undefined,
By using `undefined`, the inline styles are not used but we can instead use values from the style sheet.

2021-05-27 14:41 UTC, amannn commented on src/components/select/select.react.styles.scss
> +		}
Added styles for what was removed from the inline styles, so we can use SASS variables for theming.

2021-05-27 14:46 UTC, amannn commented on src/components/session/SessionItemComponent.tsx
> +	type: BUTTON_TYPES.SMALL_ICON
This call site was a bit tricky. The color of the small icon button is generally configured via props. However our theming only works with SASS variables currently. We could theoretically add theming via React context, but as long as we can stick to only SASS variables, I think we should do that first.

The trick here is that the grey variant is also the default of the button. Now the Diakonie can just style the default color of the button and therefore achieve the blue in their theme, while we can have the grey one for Caritas.

2021-05-27 14:47 UTC, amannn commented on src/components/session/session.styles.scss
> +	}
Small general improvement: There's now a shadow when the user scrolled up in the session.

2021-05-27 14:47 UTC, amannn commented on src/resources/styles/settings.scss
> -$background-light-ochre: #faf6f3;
Some of these were not used.

2021-05-27 14:49 UTC, amannn commented on src/resources/styles/settings.scss
> -$light-neutral: rgba(53, 58, 74, 0.1);
Some of these were not used. I've renamed `light-success` and `light-neutral` to "illustration" color variables below, since that is what they are being used for.

2021-05-27 14:50 UTC, amannn commented on src/resources/styles/settings.scss
> -$welcome-screen-icon-background: $background-accent;
I've moved these component variables below to the other ones.

2021-05-27 14:50 UTC, amannn commented on src/resources/styles/settings.scss
> -$sendInputHeight: 48px;
Also these were moved to the components section below. Keeping them at the bottom enables us to use all previously defined variables.

2021-06-02 12:59 UTC, koepferd requested changes

2021-06-02 12:59 UTC, koepferd commented on src/components/profile/DeleteAccount.tsx
> +		className: 'deleteAccount__overlay',
yeah, thanks, already fixed in the anonymous chat feature 👏🏻

2021-06-02 12:59 UTC, koepferd commented on src/components/overlay/Overlay.tsx
> +	className?: string;
This pattern is deprecated - I'd prefer it to only be in the `props`. So please add the `className` there. I will make an additional refactoring to change all overlays these days.

2021-06-02 12:59 UTC, koepferd commented on src/components/button/button.styles.scss
> +			border: none;
This shouldn't be border `none`:
![image](https://user-images.githubusercontent.com/8968377/120482067-0d052200-c3b1-11eb-878c-0587bf417561.png)
![image](https://user-images.githubusercontent.com/8968377/120482115-17bfb700-c3b1-11eb-8ce1-00d2fb0ac0c1.png)

2021-06-02 12:59 UTC, koepferd commented on src/components/button/button.styles.scss
> +			text-decoration: underline;
I don't mind it as a general improvement as long as Eileen is fine with this from the design perspective.

2021-06-02 12:59 UTC, koepferd commented on src/components/session/SessionItemComponent.tsx
> +	type: BUTTON_TYPES.SMALL_ICON
nice, good solution :-)

2021-06-04 07:31 UTC, amannn commented on src/components/button/button.styles.scss
> +			border: none;
Hmm, how were you able to trigger the below state?

To me the button looks quite identical on `develop` and in this branch:

<img width="231" alt="Screenshot 2021-06-04 at 09 25 04" src="https://user-images.githubusercontent.com/4038316/120762913-04c6f700-c517-11eb-8de0-78b6579194af.png">
<img width="254" alt="Screenshot 2021-06-04 at 09 25 46" src="https://user-images.githubusercontent.com/4038316/120762915-05f82400-c517-11eb-8902-46c66987b19f.png">

Seems like I'm missing something?

2021-06-07 08:05 UTC, amannn commented on src/components/button/button.styles.scss
> +			text-decoration: underline;
I just talked to Eileen about this style. It seems like this was a mistake and so it's removed both for Caritas and the Diakonie now.

2021-06-08 14:26 UTC, koepferd commented on src/components/button/button.styles.scss
> +			border: none;
I tried to re-create the issue and couldn't, all good.

2021-06-08 14:27 UTC, koepferd approved these changes

2021-06-09 06:46 UTC, merged