feat: improve error page styling and use translations
Onlineberatung/onlineBeratung-frontend pull request #199
Opened 2021-06-01 14:08 UTC by amannn

WIP

2021-06-02 11:27 UTC, amannn commented on src/components/error/Error.tsx
> -import '../button/button.styles';
Previously the button styles were imported without using the actual button component, but just the class names.

Somehow with the changes I made I ended up with a webpack error during the build that claimed there was a conflicting order with the stylesheets (see https://github.com/facebook/create-react-app/issues/5372). By using the full button component as well as changing the order of the styles in the login component I was able to resolve this issue.

2021-06-02 11:29 UTC, amannn commented on src/components/error/Error.tsx
> +					<h2>{translate('error.title')}</h2>
Now all strings in this component are retrieved through the translation system. We don't actually need to overwrite any of these for the Diakonie, but I figured it might be preferable anyway.

2021-06-08 14:40 UTC, koepferd requested changes

2021-06-08 14:40 UTC, koepferd commented on src/components/error/Error.tsx
> +					<h2>{translate('error.title')}</h2>
Yes, thank you :-)

2021-06-08 14:40 UTC, koepferd commented on src/components/error/Error.tsx
> +					<h2>{translate('error.title')}</h2>
Please use the existing translations for `error.title` and `error.claim` as they should always be consistent to the translations in the general app.

2021-06-09 07:03 UTC, amannn commented on src/components/error/Error.tsx
> +					<h2>{translate('error.title')}</h2>
Good idea. I've adjusted the identifier and removed the duplicate labels.

2021-06-09 09:55 UTC, koepferd approved these changes

2021-06-09 09:55 UTC, merged