refactor: apis for overview page
Onlineberatung/onlineBeratung-frontend pull request #204
Opened 2021-06-09 07:52 UTC by amannn

WIP

2021-06-21 08:19 UTC, amannn commented on src/api/apiAgencySelection.ts
> -}): Promise<[AgencyDataInterface] | null> => {
This syntax looked wrong to me and didn't work with array methods properly. As far as I know only `Array<AgencyDataInterface>` and `AgencyDataInterface[]` are valid declarations for arrays. Not sure what `[AgencyDataInterface]` means …

2021-06-21 08:19 UTC, amannn commented on src/components/app/Loading.tsx
> +			<LoadingIndicator />
I've extracted the inner part of this to a shared component that can be used for showing loading indicators.

2021-06-21 08:19 UTC, amannn commented on src/components/app/Loading.tsx
> +			setTimeout(() => setIsVisible(false), 2000)
Previously this was handled by a combination of JavaScript and styles. I've moved it to just JS now, hope that's ok!

2021-06-21 08:19 UTC, amannn commented on src/components/app/app.tsx
> +				{extraRoutes}
An abstraction that allows to add new routes specific to a given theme.

2021-06-21 08:19 UTC, amannn commented on src/components/login/Login.tsx
> +		<StageLayout stage={<Stage hasAnimation />} showLegalLinks>
The new abstraction for the stage as discussed. This avoids redundancy between the places where we used the stage so far and only requires the consumers to provide the content within the right area of the stage, without having to specify any positioning.

2021-06-21 08:19 UTC, amannn commented on src/components/registration/RegistrationForm.tsx
> -			</div>
This is also handled internally of the new stage layout.

2021-06-21 08:19 UTC, amannn commented on src/components/registration/WelcomeScreen.tsx
> -	];
Extracted to `ServiceExplanation` since we need it in the overview page as well.

2021-06-28 07:53 UTC, koepferd requested changes

2021-06-28 07:53 UTC, koepferd commented on src/api/apiAgencySelection.ts
> -}): Promise<[AgencyDataInterface] | null> => {
An error which wasn't noticed before, thanks!

2021-06-28 07:53 UTC, koepferd commented on src/components/stageLayout/StageLayout.tsx
> +					<p className="stageLayout__toLogin__text">
Please use the `<Text />` component here.

2021-06-28 07:53 UTC, koepferd commented on src/components/app/Loading.tsx
> +			<LoadingIndicator />
Nice, thanks!

2021-06-28 14:26 UTC, amannn commented on src/components/serviceExplanation/ServiceExplanation.tsx
> +				translate('registration.welcomeScreen.info4.text')
@koepferd I've added a fallback here, if no welcome screen config is provided. Is that ok? In the consulting type overview page the user doesn't have a CT selected yet to get this text from.

2021-06-28 15:27 UTC, koepferd commented on src/components/serviceExplanation/ServiceExplanation.tsx
> +				translate('registration.welcomeScreen.info4.text')
Nice, i like that, thanks!

2021-06-28 15:44 UTC, koepferd approved these changes

2021-06-29 11:35 UTC, merged