feat: support external agencies in profile registration
Onlineberatung/onlineBeratung-frontend pull request #219
Opened 2021-06-23 06:56 UTC by amannn

## Proposed Changes

  - With the upcoming agency service changes there can be external agencies where we need to forward to a landing page instead of handling the registration internally

2021-06-23 06:57 UTC, amannn commented on cypress/integration/profile.spec.ts
> +		cy.contains('Registrieren').click();
TBD: Potentially we'd want to show a hint here.

2021-06-23 18:23 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +				...proposedAgencies.find((cur) => cur.id === selectedAgencyId),
We need the `external` and `url` property.

2021-06-23 18:24 UTC, amannn commented on src/components/profile/AskerRegistrationExternalAgencyOverlay.tsx
> +		</OverlayWrapper>
Maybe there will be some design changes here, I've asked Eileen if we can reuse some default styles (see Teams group chat).

2021-06-23 18:24 UTC, amannn commented on src/resources/scripts/i18n/de/profile.ts
> +		'“ zu der anderen Anwendung wechseln und sich dort registrieren? Ihre bisherigen Beratungs- und Hilfethemen finden Sie weiterhin hier.',
Since I need to interpolate a consulting type title into the label, is it the right way to split the label into two?

2021-06-25 16:14 UTC, koepferd requested changes

2021-06-25 16:14 UTC, koepferd commented on src/components/profile/AskerRegistrationExternalAgencyOverlay.tsx
> +				consultingType.urls.registrationPostcodeFallbackUrl;
As far as I understood in this case the `selectedAgency.url` would be used, right?
`registrationPostcodeFallbackUrl` is another specific use case in the scope of a consultingType and is only given when a consultingType doesn't have a white spot agency.

2021-06-25 16:14 UTC, koepferd commented on src/components/profile/AskerRegistrationExternalAgencyOverlay.tsx
> +		</OverlayWrapper>
Yes, we still have to work on the general overlay styles for desktop: 
- icon left not center top
- buttons bottom right and next to each other

2021-06-25 16:14 UTC, koepferd commented on cypress/fixtures/service.consultingtypes.addiction.json
> +	"urls": {
See `AskerRegistrationExternalAgencyOverlay.tsx`, I think this is the wrong mock. This case should be tested for an agency not consultingType.

2021-06-25 16:14 UTC, koepferd commented on cypress/integration/profile.spec.ts
> +		cy.contains('Registrieren').click();
What do you mean? Let's discuss on monday.

2021-06-25 16:14 UTC, koepferd commented on src/components/profile/AskerRegistrationExternalAgencyOverlay.tsx
> +				consultingType.urls.registrationPostcodeFallbackUrl;
In addition, does it make sense to open the registration page of the agency in a new window instead of in the same tab in regards of usability? As a user I'd might check the offer of the agency and decide against it. Should be discussed with concept I think.

2021-06-28 08:31 UTC, amannn commented on src/components/profile/AskerRegistrationExternalAgencyOverlay.tsx
> +				consultingType.urls.registrationPostcodeFallbackUrl;
You're of course right, thanks for noticing this! Should be fixed now.

2021-06-28 16:00 UTC, koepferd approved these changes, later dismissed

2021-06-29 15:52 UTC, koepferd submitted a review, later dismissed

2021-06-29 15:56 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +				...proposedAgencies.find((cur) => cur.id === selectedAgencyId),
`proposedAgencies` can be `null` during the registration. I'm currently investigating why this causes some tests on [the Diakonie side to fail](https://github.com/virtualidentityag/diakonie-onlineBeratung-frontend-theme/pull/9/checks?check_run_id=2943194125), but not here …

2021-06-29 18:30 UTC, amannn commented on src/components/agencySelection/AgencySelection.tsx
> +				...proposedAgencies?.find((cur) => cur.id === selectedAgencyId),
In the case of the registration outside of the app this can be undefined. We only need the `id` and `postcode` for that use case though and therefore this is sufficient.

2021-06-30 06:12 UTC, koepferd approved these changes, later dismissed

2021-06-30 08:40 UTC, koepferd approved these changes

2021-06-30 08:43 UTC, merged