Feature optimize websocket
Onlineberatung/onlineBeratung-frontend pull request #241
Opened 2021-09-17 12:39 UTC by mebo4b

## Optimize performance

 - Prevent rocket chat websocket connection for all enquiries
 - Filter websocket events from technical rocket chat user to prevent multiple reloads of sessions

2021-09-28 12:15 UTC, koepferd commented on src/api/rocketChatSocket.ts
> +						'cob-rocket-chat-technical-user'
Is this user on all systems named exactly the same?
I'd suggest a more generic name without 'cob' to reduce the client specifica. I am aware that you'd have to change the name of the technical user for that. Is the effort for that manageable?
I'd rather invest some time for this here as we can then use the generic name for the documentation and can be used by every instance of the onlineberatung and be less error-prone.
What do you think?

2021-09-28 12:16 UTC, koepferd requested changes
See comment in rocketChatSocket.ts

2021-10-06 08:23 UTC, mebo4b commented on src/api/rocketChatSocket.ts
> +						'cob-rocket-chat-technical-user'
This expression matches for all systems hosted for caritas right now yes, but i agree with aspect having a unique generic technical username for all instances and would suggest having just the name 'rocket-chat-technical-user'. Changing the name is not that much effort so i would start adapt and document the changes ;-)

2021-10-06 09:25 UTC, koepferd approved these changes

2021-10-06 09:32 UTC, merged