DDO-21 Statistic CSV
Onlineberatung/onlineBeratung-frontend pull request #314
Opened 2022-01-12 15:04 UTC by alxbenz

## Proposed Changes

  - changed csv to match selected time period
  - removed active consultations

2022-01-14 08:16 UTC, web-mi submitted a review, later dismissed

2022-01-14 11:35 UTC, koepferd requested changes
Hi @alxbenz,
sorry, there was a misunderstanding on the what the "Aktive Beratungen" are. I discussed this with the client and we will keep the "numberOfSessionsWhereConsultantWasActive" in the export file (I've added further information in the ticket).

Could you please revert this? Sorry for the double work.

2022-01-14 12:30 UTC, alxbenz commented
@koepferd no worries. I reverted the changes.

2022-01-17 10:05 UTC, koepferd requested changes

2022-01-17 10:05 UTC, koepferd commented on src/resources/scripts/i18n/de/profile.ts
> +		'Ihre Statistik über Ihren gewählten Beratungszeitraum können Sie hier herunterladen:',
Can you please also change the wording for the informal translatable to "gewählten"? Thank you.

2022-01-17 10:52 UTC, koepferd approved these changes

2022-01-17 10:52 UTC, merged