feat: [DDO-44] registration by cid
Onlineberatung/onlineBeratung-frontend pull request #336
Opened 2022-01-31 02:39 UTC by web-mi

Fixes #DDO-44

## Proposed Changes

  - added "cid" to registration url to be able to register for consultant
  - changed fetchData to handle CATCH_ALL at the end
  -

2022-01-31 11:13 UTC, koepferd requested changes

2022-01-31 11:13 UTC, koepferd commented on src/resources/scripts/i18n/de/registrationInformal.ts
> +		'Bitte registriere dich, um mit deinem Berater in Kontakt zu kommen'
Typo, please write *Dich

2022-01-31 11:13 UTC, koepferd commented on src/components/registration/RegistrationPassword.tsx
> +				setPasswordLabelState(VALIDITY_VALID);
please remove duplication

2022-01-31 11:13 UTC, koepferd commented on src/components/registration/RegistrationAge.tsx
> +		age ? setIsValid('valid') : setIsValid(VALIDITY_INITIAL);
please also use VALIDITY_VALID in case age is set.

2022-01-31 11:13 UTC, koepferd commented on src/components/registration/RegistrationForm.tsx
> +	}, [consultant.consultantId, formAccordionData, setAcceptedGroupId]);
breaks the normal registration flow as the consultant is optional

2022-01-31 11:13 UTC, koepferd commented on src/components/registration/Registration.tsx
> +						title={consultingType?.titles.welcome || 'Welcome'}
Please use a translation variable and correct text (no english, discuss with concept) for the alternative without consulting type

2022-01-31 11:13 UTC, koepferd commented on src/api/fetchData.ts
> +					} else if (
should be before line 146 which only checks for response.status

2022-01-31 11:13 UTC, koepferd commented on src/components/registration/Registration.tsx
> +		aid: agencyId
AFAIK aid is not used as a param for login. Please remove this.

2022-01-31 13:31 UTC, web-mi commented on src/components/registration/Registration.tsx
> +		aid: agencyId
aid will preselect the agency of a consultant if it exists on the consultant

2022-01-31 17:03 UTC, koepferd requested changes

2022-01-31 17:03 UTC, koepferd commented on src/resources/scripts/i18n/de/registration.ts
> +		'Ihr Berater ist in mehreren Themenfeldern tätig. Bitte wählen Sie Ihr gewünschtes Themenfeld.',
Please use gender gap for "Berater", same in line 117.

2022-01-31 17:03 UTC, koepferd commented on src/resources/scripts/i18n/de/registrationInformal.ts
> +		'Dein Berater ist in mehreren Themenfeldern tätig. Bitte wähle Dein gewünschtes Themenfeld.',
Same as in registration.ts -> gender gap for Berater

2022-02-03 17:16 UTC, koepferd approved these changes

2022-02-03 17:24 UTC, merged