Feature refactor registration
Onlineberatung/onlineBeratung-frontend pull request #39
Opened 2020-10-09 15:14 UTC by iam-robin

Fixes #

## Proposed Changes

  - add react registration component with real time validation
  - remove old hbs registration

2020-10-13 09:53 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +	const inputItempassword: InputFieldItem = {
Typo: please use camelCase: *inputItemPassword

2020-10-13 12:29 UTC, koepferd commented on src/resources/ts/i18n/de/registration.ts
> +	'email.valid': 'Ihre E-Mail-Adresse ist gültig',
line 29 & 30, please use full stop at the end of the sentence to be consistent to other error messages

2020-10-13 12:29 UTC, koepferd commented on src/resources/ts/i18n/de/registrationInformal.ts
> +	'email.valid': 'Deine E-Mail-Adresse ist gültig',
line 18 & 19, please use full stop at the end of the sentence to be consistent to other error messages

2020-10-13 12:34 UTC, koepferd commented on src/pages/registration.html
> +			data-resortName="<%= resortName %>"
Is there a specific reason, why you would pass the resortNames from webpack as a data-attribute?
You can just use the consultingType and the getResortKeyForConsultingType(currentConsultingType) helper function to get the resortName.

2020-10-13 12:36 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +		const resortName = document.getElementById('registrationRoot').dataset
You can use the getResortKeyForConsultingType() helper function with the consultingType from the dataset. No need to access the dom and pass the resortName from webpack to the compiled html file.

2020-10-13 12:37 UTC, koepferd commented on webpack.config.js
> +				resortName: 'addiction'
No need to pass the resortName for any of the consultingTypes, please see comments in the registration.html & Registration.tsx

2020-10-13 14:00 UTC, koepferd commented on src/components/registration/registrationData.js
> +	gemeinsamstatteinsam: {
Please use correct ageSelect values for gemeinsamstatteinsam, they differ from the u25 registration

2020-10-13 14:23 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +const getValidationClassNames = (invalid, valid) => {
please put this function in the helper file

2020-10-13 14:36 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +	const [generatedInputfieldValues, setGeneratedInputfieldValues] = useState(
Please reconsider naming here. For me the meaning is not clear.

2020-10-13 14:43 UTC, koepferd commented on src/components/postcodeSuggestion/ts/PostcodeSuggestion.tsx
> +import * as React from 'react';
Lets reconsider this component and related function naming, for me it is rather an agencySuggestion, or agencyProposal.

2020-10-13 14:45 UTC, koepferd commented on src/components/postcodeSuggestion/ts/PostcodeSuggestion.tsx
> +											<svg
Please use the iconHelper for this svg

2020-10-14 06:28 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +	const buttonItemSubmit: ButtonItem = {
Can be extracted to helper file.

2020-10-14 06:29 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +	const [password, setpassword] = useState(null);
please use camelCase for setPassword

2020-10-14 06:38 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +					className="test-class-lol"
Please remove class.

2020-10-14 06:42 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +								id: 'editGroupChat'
Please remove incorrect id. No id needed here.

2020-10-14 09:18 UTC, iam-robin commented on src/components/postcodeSuggestion/ts/PostcodeSuggestion.tsx
> +import * as React from 'react';
you're right. `agencySelection` makes the most sense to me. What do you think?

2020-10-14 09:25 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +	const [generatedInputfieldValues, setGeneratedInputfieldValues] = useState(
renamed the state to `valuesOfGeneratedInputs` to make clear, that the input fields are generated and not the values. What do you think?

2020-10-14 09:34 UTC, iam-robin commented on src/pages/registration.html
> +			data-resortName="<%= resortName %>"
yes there is a reason:
As u25 and gemeinsamstatteinsam have the same consultingType, we can't load the data based on the consultingType, but need the agency name.

2020-10-14 09:35 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +		const resortName = document.getElementById('registrationRoot').dataset
see comment above in `registration.html`.

2020-10-14 09:35 UTC, iam-robin commented on webpack.config.js
> +				resortName: 'addiction'
see comment above in `registration.html`.

2020-10-14 10:03 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +	const [generatedInputfieldValues, setGeneratedInputfieldValues] = useState(
Love it!

2020-10-14 11:20 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +	const inputItempassword: InputFieldItem = {
done 👍

2020-10-14 11:20 UTC, iam-robin commented on src/resources/ts/i18n/de/registration.ts
> +	'email.valid': 'Ihre E-Mail-Adresse ist gültig',
done 👍

2020-10-14 11:20 UTC, iam-robin commented on src/resources/ts/i18n/de/registrationInformal.ts
> +	'email.valid': 'Deine E-Mail-Adresse ist gültig',
done 👍

2020-10-14 11:20 UTC, iam-robin commented on src/pages/registration.html
> +			data-resortName="<%= resortName %>"
nothing to do here

2020-10-14 11:21 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +		const resortName = document.getElementById('registrationRoot').dataset
nothing to do here

2020-10-14 11:21 UTC, iam-robin commented on webpack.config.js
> +				resortName: 'addiction'
nothing to do here

2020-10-14 11:21 UTC, iam-robin commented on src/components/registration/registrationData.js
> +	gemeinsamstatteinsam: {
done 👍

2020-10-14 11:21 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +const getValidationClassNames = (invalid, valid) => {
done 👍

2020-10-14 11:21 UTC, iam-robin commented on src/components/postcodeSuggestion/ts/PostcodeSuggestion.tsx
> +											<svg
done 👍

2020-10-14 11:22 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +	const buttonItemSubmit: ButtonItem = {
done 👍

2020-10-14 11:22 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +	const [password, setpassword] = useState(null);
done 👍

2020-10-14 11:22 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +					className="test-class-lol"
done 👍

2020-10-14 11:22 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +								id: 'editGroupChat'
done 👍

2020-10-14 11:22 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +	const [generatedInputfieldValues, setGeneratedInputfieldValues] = useState(
done 👍

2020-10-14 11:52 UTC, iam-robin commented on src/components/postcodeSuggestion/ts/PostcodeSuggestion.tsx
> +import * as React from 'react';
done 👍

2020-10-14 11:57 UTC, koepferd commented on src/components/select/ts/select.ts
>  import customSelect from 'custom-select';
This file is not used anymore, please remove it.

2020-10-14 11:58 UTC, koepferd commented on src/components/registration/scaffolding/registration-demo.hbs
> +<div id="registrationRoot" data-resources="[{paths: ['components/registration/ts/initRegistration.js?{{bioTrueEnv 'RELEASE_VERSION'}}']}]">
Please remove this file as it isn't used anymore.

2020-10-14 12:16 UTC, koepferd commented on src/components/agencySelection/ts/AgencySelection.tsx
> +	const [suggestedAgencies, setSuggestedAgencies] = useState(null);
It's sugaring, but I'd love to rename it to proposedAgencies 😬
Only if you find time for this 😉

2020-10-14 13:35 UTC, iam-robin commented on src/components/select/ts/select.ts
>  import customSelect from 'custom-select';
done 👍

2020-10-14 13:36 UTC, iam-robin commented on src/components/registration/scaffolding/registration-demo.hbs
> +<div id="registrationRoot" data-resources="[{paths: ['components/registration/ts/initRegistration.js?{{bioTrueEnv 'RELEASE_VERSION'}}']}]">
done 👍

2020-10-14 13:36 UTC, iam-robin commented on src/components/agencySelection/ts/AgencySelection.tsx
> +	const [suggestedAgencies, setSuggestedAgencies] = useState(null);
no worries – done 👍

2020-10-14 13:49 UTC, koepferd requested changes

2020-10-14 13:49 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +			removeWarningLabels();
Please differentiate removeWarningLabels() for both cases, so they don't get all removed, once you change one of the two fields.

2020-10-14 15:11 UTC, iam-robin commented on src/components/registration/ts/Registration.tsx
> +			removeWarningLabels();
done 👍

2020-10-15 09:38 UTC, koepferd approved these changes, later dismissed
Please await browser testing before merging this feature.

2020-10-20 09:17 UTC, koepferd requested changes

2020-10-20 09:17 UTC, koepferd commented on src/components/overlay/ts/Overlay.tsx
> +			(buttonFunction === OVERLAY_FUNCTIONS.REDIRECT &&
Instead of added a new class please add a new overlay function for this use case of a redirect without the removal of the blur.

2020-10-20 09:17 UTC, koepferd commented on src/pages/registration.html
> +		<div id="overlay" class="overlay--keepBlur"></div>
Remove this class please. See comment in Overlay.tsx

2020-10-21 06:52 UTC, koepferd commented on src/components/overlay/ts/Overlay.tsx
> +	REDIRECTWITHBLUR: 'REDIRECTWITHBLUR',
Please rename to "REDIRECT_WITH_BLUR" to follow naming conventions

2020-10-21 06:53 UTC, koepferd commented on src/components/inputField/scss/_inputField.styles.scss
> +// .formWrapper {
Please remove unused styles

2020-10-21 06:54 UTC, koepferd commented on src/components/registration/ts/Registration.tsx
> +				<h3 className="registration__layline">{resortData.overline}</h3>
please fix class name "registration__overline"

2020-10-21 06:56 UTC, koepferd requested changes
Please see new comments for requested changes.

2020-10-21 10:59 UTC, koepferd submitted a review, later dismissed

2020-10-26 14:51 UTC, koepferd commented on src/resources/ts/helpers/resorts.ts
>  export const isRehabilitationRegistration = () =>
Pls check and remove: isRehabilitationRegistration() and isKreuzbundRegistration() should be unused now

2020-10-26 15:22 UTC, koepferd requested changes
Please see comment above

2020-10-26 15:36 UTC, iam-robin commented on src/resources/ts/helpers/resorts.ts
>  export const isRehabilitationRegistration = () =>
you're right. I've removed the unused functions.

2020-10-26 15:42 UTC, koepferd approved these changes

2020-10-27 09:24 UTC, merged