refactor: 💡 textarea focus and resizing
Onlineberatung/onlineBeratung-frontend pull request #390
Opened 2022-03-10 13:56 UTC by koepferd

## Proposed Changes

  - fix: click on placeholder in textarea focusses the editor and is ready to type
  - refactor resizing logic

2022-03-12 11:54 UTC, web-mi requested changes

2022-03-12 11:54 UTC, web-mi commented on src/components/messageSubmitInterface/messageSubmitInterface.styles.scss
> +			width: calc(100% - #{1px});
```suggestion
			width: calc(100% - 1px);
```

2022-03-12 11:54 UTC, web-mi commented on src/components/messageSubmitInterface/messageSubmitInterfaceComponent.tsx
> +							handleSendButton={(event) =>
```suggestion
							handleSendButton={handleButtonClick}
```

2022-03-12 11:54 UTC, web-mi commented on src/components/messageSubmitInterface/messageSubmitInterfaceComponent.tsx
> +								handleButtonClick(event)
```suggestion
```

2022-03-12 11:54 UTC, web-mi commented on src/components/messageSubmitInterface/messageSubmitInterfaceComponent.tsx
> +							}
```suggestion
```

2022-03-12 11:54 UTC, web-mi commented on src/components/messageSubmitInterface/messageSubmitInterfaceComponent.tsx
> +			textareaMaxHeight = 118;
We schould consider if it makes sense to use styled-components in this case

2022-03-14 13:34 UTC, koepferd commented on src/components/messageSubmitInterface/messageSubmitInterfaceComponent.tsx
> +			textareaMaxHeight = 118;
As discussed, generally yes, not in the scope of the bugfix more me though.
Let's take this to the story about general style improvements :-)

2022-03-14 15:48 UTC, web-mi approved these changes

2022-03-14 15:49 UTC, merged