[WIP] feat: [COBH-4210] e2ee support check
Onlineberatung/onlineBeratung-frontend pull request #396
Opened 2022-03-16 15:05 UTC by web-mi

Fixes #COBH-4210

## Proposed Changes

  - Added check for e2ee support
  - Added info if e2ee is not available
  - Blocking calls for Berater if e2ee is not supported
  - Added links to help page
  - Added e2ee parameter to jitsi url

2022-03-22 08:11 UTC, koepferd requested changes

2022-03-22 08:11 UTC, koepferd commented on src/resources/scripts/i18n/de/videoCall.ts
> +		'Durch die technischen Vorraussetzungen ist der Video-Call nicht Ende-zu-Ende verschlüsselt. Bitte folgen Sie der Hilfe um Ende-zu-Ende verschlüsselt zu telefonieren.',
Please check with concept. There is an updated hint text.

2022-03-22 08:11 UTC, koepferd commented on src/resources/scripts/i18n/de/videoCallInformal.ts
> +		'Durch die technischen Vorraussetzungen ist der Video-Call nicht Ende-zu-Ende verschlüsselt. Bitte folge der Hilfe um Ende-zu-Ende verschlüsselt zu telefonieren.',
Please check with concept. There is an updated hint text.

2022-03-22 08:11 UTC, koepferd commented on src/components/sessionMenu/SessionMenu.tsx
> +			window.location.href = '/help/videoCall';
Route got updated to '/hilfe/videoCall'.

2022-03-22 08:11 UTC, koepferd commented on src/components/incomingVideoCall/IncomingVideoCall.tsx
> +								(window.location.href = '/help/videoCall')
Please adjust route to help page.

2022-03-24 14:46 UTC, alxbenz commented on src/components/incomingVideoCall/incomingVideoCall.styles.scss
> +			margin-bottom: 24px;
Maybe use $grid-base-three here

2022-03-24 14:46 UTC, alxbenz commented on src/components/incomingVideoCall/incomingVideoCall.styles.scss
> +		margin-top: 10px;
$grid-base might be enough here?

2022-03-24 14:46 UTC, alxbenz commented on src/components/notifications/Notification.tsx
> +	}, [notification]); // eslint-disable-line react-hooks/exhaustive-deps
can you add the dependencies here?

2022-03-24 14:46 UTC, alxbenz commented on src/components/notifications/Notification.tsx
> +	const icon = getIcon();
Do we need "useCallback" on the function, since this will be called every render anyway?

2022-03-24 14:46 UTC, alxbenz commented on src/resources/scripts/i18n/de/videoCall.ts
> +	'incomingCall.unsupported.description': 'Video-Call von %username%',
❤️

2022-03-24 14:46 UTC, alxbenz submitted a review, later dismissed

2022-03-25 15:25 UTC, alxbenz approved these changes

2022-03-28 06:03 UTC, koepferd approved these changes

2022-03-28 14:18 UTC, merged