Obi 5 display name
Onlineberatung/onlineBeratung-frontend pull request #407
Opened 2022-04-01 12:12 UTC by alxbenz

2022-04-08 07:57 UTC, koepferd commented on src/api/apiForwardMessage.ts
> +		username: displayName, // TODO change to displayName if message service is adjusted
This can be updated now :-)
https://github.com/CaritasDeutschland/caritas-onlineBeratung-messageService/pull/78/files

2022-04-08 08:38 UTC, alxbenz commented on src/api/apiForwardMessage.ts
> +		username: displayName, // TODO change to displayName if message service is adjusted
I just talked to Torsten and username is still a required parameter. 
This change is rather to make sure the backend logs are not showing an error. 

So no, we can not change this to displayName currently.

2022-04-11 08:07 UTC, koepferd commented on src/api/apiForwardMessage.ts
> +		username: displayName, // TODO change to displayName if message service is adjusted
Ok, thank you for clarification!

2022-04-11 08:18 UTC, koepferd requested changes

2022-04-11 08:18 UTC, koepferd commented on src/resources/scripts/i18n/de/profileInformal.ts
> +	'data.info.public':
Please use *Du to stay consistent

2022-04-12 08:12 UTC, koepferd approved these changes

2022-04-13 06:54 UTC, merged