Obi 20
Onlineberatung/onlineBeratung-frontend pull request #409
Opened 2022-04-06 12:29 UTC by alxbenz

2022-04-10 19:08 UTC, web-mi requested changes

2022-04-10 19:08 UTC, web-mi commented on src/components/releaseNote/ReleaseNote.tsx
> +	console.log(showReleaseNote);
REM
```suggestion
```

2022-04-10 19:08 UTC, web-mi commented on src/components/releaseNote/ReleaseNote.tsx
> +	if (!showReleaseNote || hasSeenReleaseNote) return <></>;
```suggestion
	if (!showReleaseNote || hasSeenReleaseNote) return null;
```

2022-04-10 19:08 UTC, web-mi commented on cypress/integration/video-calls.spec.ts
> +		cy.intercept('GET', '/releases/*', { statusCode: 404 });
You could move this to mockApi.ts with 
`defaultReturns['releases']={ statusCode: 404}`
and
```
cy.intercept('GET', '/releases/*, (req) => {
		req.reply({
			...defaultReturns['releases'],
			...(overrides['releases'] || {})
		});
	}).as('releases');
```
And then just use cy.willReturn('releases', ...);
where you need it in your tests. Then we won't have problems in other tests where it should not return anything. ;-)

2022-04-10 19:08 UTC, web-mi commented on src/components/overlay/overlay.styles.scss
> +			margin-top: ((-$size / 2) - $grid-base-six);
Is this a fix for the overlay with illustration cut off?
Haven't seen it so i made one in OBI-13 too with fixing scroll etc. :-)

2022-04-10 19:08 UTC, web-mi commented on src/components/releaseNote/ReleaseNote.tsx
> +			`${uiUrl}/releases/v${packageInfo.version}.md`
Move url to config.ts
```suggestion
			`${config.urls.releases}/v${packageInfo.version}.md`
```

2022-04-11 10:05 UTC, web-mi approved these changes

2022-04-11 10:06 UTC, web-mi requested changes

2022-04-11 10:06 UTC, web-mi commented on cypress/integration/video-calls.spec.ts
> +		cy.intercept('GET', '/releases/*', { statusCode: 404 });
This line could be removed now?
```suggestion
```

2022-04-11 11:39 UTC, alxbenz commented on cypress/integration/video-calls.spec.ts
> +		cy.intercept('GET', '/releases/*', { statusCode: 404 });
I can't find this anymore... Did you perhaps check an older commit?

2022-04-12 10:29 UTC, web-mi submitted a review, later dismissed

2022-04-13 07:19 UTC, web-mi approved these changes

2022-04-13 07:20 UTC, merged