fix: [OBI-157] added video call list view and add overlay
Onlineberatung/onlineBeratung-frontend pull request #414
Opened 2022-04-10 13:42 UTC by web-mi

Fixes #OBI-157

## Proposed Changes

  - Implemented first version of waiting room
  - Implemented videocall appointments Listing with CRUD functions
  - Implemented video call integration routes and videocall

2022-04-11 12:36 UTC, koepferd requested changes, later dismissed

2022-04-11 12:36 UTC, koepferd commented on src/resources/scripts/i18n/de/videoConferenceInformal.ts
> +		'Der Video-Call hat noch nicht begonnen. Du wirst weitergeleitet sobald dein/e Berater/in den Video-Call startet.'
For the open source core please always use the gender gap: _

2022-04-11 12:36 UTC, koepferd commented on src/resources/scripts/i18n/de/videoConference.ts
> +		'Der Video-Call hat noch nicht begonnen. Sie werden weitergeleitet sobald ihr/e Berater/in den Video-Call startet.',
For the open source core please always use the gender gap: _

2022-04-11 12:36 UTC, koepferd commented on src/components/appointment/Appointment.tsx
> +		label: 'Videocall starten',
Please use a translation key here.

2022-04-11 12:36 UTC, koepferd commented on src/components/appointment/Appointments.tsx
> +			// ToDo: Implement API call
Remove comment please, as it is implemented

2022-04-27 08:17 UTC, alxbenz approved these changes

2022-04-27 08:18 UTC, merged