feat: [OBI-459] re-encrypt room for users who lost their master key
Onlineberatung/onlineBeratung-frontend pull request #456
Opened 2022-06-10 06:42 UTC by Franjoo

- re-encrypt room for users who lost their master key

2022-06-10 11:35 UTC, alxbenz requested changes

2022-06-10 11:35 UTC, alxbenz commented on src/hooks/useE2EE.tsx
> +	const UpdateRoomKeysIfNecessary = useCallback(async () => {
can you use a smallcase update here?

2022-06-10 11:35 UTC, alxbenz commented on src/hooks/useE2EE.tsx
> +		UpdateRoomKeysIfNecessary();
see above

2022-06-14 07:11 UTC, Franjoo commented on src/hooks/useE2EE.tsx
> +	const UpdateRoomKeysIfNecessary = useCallback(async () => {
sorry, of course.. I've overlooked it

2022-06-14 07:14 UTC, merged