feat: [OBI-333] change wording
Onlineberatung/onlineBeratung-frontend pull request #469
Opened 2022-06-13 09:47 UTC by MelanieJakobArbeit

Fixes #

## Proposed Changes

  -
  -
  -

2022-06-13 09:55 UTC, web-mi requested changes

2022-06-13 09:55 UTC, web-mi commented on src/resources/scripts/i18n/de/videoConference.ts
> +		'Sie wurden nicht zugelassen. Leider können Sie an diesem Video-Call nicht teilnehmen, da Ihr:e Berater:in Sie nicht zugelassen hat.',
Bei Caritas wird immer mit _ gendert. 
: nur bei Diakonie. Wie es für Onlineberatung selbst weiß ich nicht aber aktuell ist noch alles mit _

2022-06-13 09:58 UTC, MelanieJakobArbeit commented on src/resources/scripts/i18n/de/videoConference.ts
> +		'Sie wurden nicht zugelassen. Leider können Sie an diesem Video-Call nicht teilnehmen, da Ihr:e Berater:in Sie nicht zugelassen hat.',
Ok danke für den Hinweis, änder ich sofort. Hatte es jetzt einfach vom Konzept kopiert und gar nicht drüber nachgedacht.

2022-06-14 06:58 UTC, alxbenz approved these changes

2022-06-14 07:01 UTC, web-mi approved these changes

2022-06-14 07:21 UTC, merged