Obi 369
Onlineberatung/onlineBeratung-frontend pull request #470
Opened 2022-06-14 05:58 UTC by MelanieJakobArbeit

Fixes #

## Proposed Changes

  -
  -
  -

2022-06-14 07:20 UTC, alxbenz requested changes

2022-06-14 07:20 UTC, alxbenz commented on src/components/profile/ConsultantNotifications.tsx
> +	const [isActivated, setIsActivated] = useState(false);
can we rename this variable, to represent the actual toggle it changes? Then we won't need to change it in the future if there are additional toggles added.

2022-06-14 07:20 UTC, alxbenz commented on src/components/profile/ConsultantNotifications.tsx
> +		setUserData(updatedUserData);
Maybe wait until the patch user data call done to update the user data in case there is an error from the backend.

2022-06-14 07:20 UTC, alxbenz commented on src/components/profile/ConsultantNotifications.tsx
> +		<div className="notifivations">
typo

2022-06-14 07:20 UTC, alxbenz commented on src/components/profile/ConsultantNotifications.tsx
> +			{userData.emailToggles.length > 0 && (
Does it make sense to show the headline and subline if there is no toggle?

2022-06-14 07:27 UTC, web-mi requested changes

2022-06-14 07:27 UTC, web-mi commented on src/components/profile/ConsultantNotifications.tsx
> +	const [isActivated, setIsActivated] = useState(false);
I think we don't need this state anyway becuase all data alredy in userData.emailToggles.
Just map the toggles.
On click send the new values.
Update UserData by useUpdateUserData hook.

Maybe keep a clone of userData.emailToggles in a state so the toggle changes before requests are finished.

2022-06-14 07:47 UTC, alxbenz commented on src/components/profile/ConsultantNotifications.tsx
> +	const [isActivated, setIsActivated] = useState(false);
Even better ;)

2022-06-14 08:04 UTC, web-mi submitted a review, later dismissed

2022-06-14 08:04 UTC, web-mi commented on src/components/profile/ConsultantNotifications.tsx
> +						<Switch
userData.emailToggles.map((emailToggle) => ...)

2022-06-14 08:04 UTC, web-mi commented on src/components/profile/ConsultantNotifications.tsx
> +							checked={isFollowUpMessagesActivated}
checked={emailToggle.state}

2022-06-14 08:04 UTC, web-mi commented on src/components/profile/ConsultantNotifications.tsx
> +							text={translate('profile.notifications.label')}
text={translate(`profile.notifications.label.${emailToggle.name}`)}

2022-06-17 07:40 UTC, alxbenz approved these changes

2022-06-17 07:40 UTC, alxbenz commented on src/resources/scripts/config.ts
> +export const emails = {
I am not sure if we should put this in the global config or if it would be better inside the Notifications component, since it is not used anywhere else. What do you think?

2022-06-20 13:02 UTC, alxbenz approved these changes

2022-06-20 13:08 UTC, merged