OBI-431
Onlineberatung/onlineBeratung-frontend pull request #489
Opened 2022-06-28 06:55 UTC by Franjoo

- handle master key lost scenario
  - show info message + overlay
  - send / receive special system alias message
  - find out ability to send info message

2022-07-01 07:45 UTC, alxbenz commented on src/components/message/MessageItemComponent.tsx
> +								dangerouslySetInnerHTML={{
Does this need to be set as HTML?
Wouldn't <span>{translate(...)}</span> suffice here?

2022-07-01 07:48 UTC, alxbenz commented on src/components/session/SessionItemComponent.tsx
> +	// const canDecrypted = useCallback(() => {
Can we remove this?

2022-07-01 09:29 UTC, alxbenz commented
I changed some minor stuff.
But during my testing this was not working as intended... Probably because this was referencing and older version of e2ee (since then we change the useE2ee hook to not trigger in all the list items, as well as changed the subscriptions to use the websocket instead of the API).
@Franjoo can you have a look again?
I could not send an Alias Message after losing the masterKey. And the other user was not able to reset my subscription key.
Feel free to contact me next week for a quick chat.

2022-07-07 14:11 UTC, Franjoo commented
> I changed some minor stuff. But during my testing this was not working as intended... Probably because this was referencing and older version of e2ee (since then we change the useE2ee hook to not trigger in all the list items, as well as changed the subscriptions to use the websocket instead of the API). @Franjoo can you have a look again? I could not send an Alias Message after losing the masterKey. And the other user was not able to reset my subscription key. Feel free to contact me next week for a quick chat.

The problem why the update group key mechanic not worked as intended anymore was caused by a more recent change in the addNewUsersToEncryptedRoom function. More precisely:

```
const { users } = await apiRocketChatGetUsersOfRoomWithoutKey(rid);

// we can stop this request if there are only system and technical user without keys
if (users.length <= 2) { // <- that was always true in case of master key lost. setting 2 to 1 solved the issue and got it working again  
  return;
}
```

Besides from that, I noticed your changes included the introduction of the possibility to send unencrypted messages while normally sending encrypted ones. I used your new login and changed the message type when sending the master key lost info. Now an unencrypted user message is sent instead of a system message. That has the advantage, that is is clear which participant has send the info message in the past. (That would be unclear if both participant have a decrypted chat / present master keys; the participant with a decrypted chat would think that the other could not decrypt anymore). 
If thats not entirely clear, lets have a chat after your vacation ;)

2022-07-07 16:05 UTC, web-mi requested changes

2022-07-07 16:05 UTC, web-mi commented on src/resources/styles/settings.scss
> +$message-submit-interface-encryption-notice-info-wrapper-disabled: rgba(
Oben bitte 
$black-5-opacity: rgba(0, 0, 0, 0.5);
definieren und hier verwenden.
Dann bitte auch gleich bei $tab-background-color nutzen

2022-07-07 16:05 UTC, web-mi commented on src/resources/scripts/i18n/de/session.ts
> +	'encrypted.notice.send.first':
first und second kannst du in einen Satz mit einem Platzhalter packen den du dann beim translate(..., {platzhalter: 'xy'}) übergeben kannst. 
Siehe qrCode.ts -> download.filename

2022-07-07 16:05 UTC, web-mi commented on src/resources/scripts/i18n/de/sessionInformal.ts
> +	'encrypted.notice.send.first':
Same like session.ts. 
first und second durch platzhalter ersetzten

2022-07-07 16:05 UTC, web-mi commented on src/resources/scripts/i18n/de/sessionInformal.ts
> +		'Deine Nachrichten sind aus Sicherheitsgründen Ende-zu-Ende verschlüsselt. Das bedeutet, niemand außerhalb dieses Chats kann die Nachrichten lesen. Nicht einmal die Online-Beratungs-Plattform. <br/
```suggestion
		'Deine Nachrichten sind aus Sicherheitsgründen Ende-zu-Ende verschlüsselt. Das bedeutet, niemand außerhalb dieses Chats kann die Nachrichten lesen. Nicht einmal die Online-Beratungs-Plattform. <br/><br/>Da Du Dein Passwort zurückgesetzt hast, sind die Nachrichten für Dich momentan nicht lesbar. Sobald ',
```

2022-07-07 16:06 UTC, web-mi requested changes

2022-07-07 16:06 UTC, web-mi commented on src/resources/scripts/i18n/de/session.ts
> +	'encrypted.overlay.button': 'Schliessen',
```suggestion
	'encrypted.overlay.button': 'Schließen',
```
Bitte überall gleich ersetzten. Wir haben aktuell einen Mix aus Schliessen und Schließen

2022-07-13 07:11 UTC, closed without merging