Obi-589 password reset warn overlay
Onlineberatung/onlineBeratung-frontend pull request #502
Opened 2022-07-06 13:39 UTC by Franjoo

password reset warn overlay

2022-07-06 14:44 UTC, web-mi requested changes

2022-07-06 14:44 UTC, web-mi commented on src/resources/scripts/i18n/de/login.ts
> +		'Durch das Zurücksetzten des Passworts kann der Zugriff auf Ihre Nachrichten eventuell nicht mehr gewährleistet werden.',
Bitte auch noch in die loginInformal.ts

2022-07-06 14:44 UTC, web-mi commented on src/resources/scripts/i18n/de/login.ts
> +		'Möchten Sie das Passwort dennoch zurücksetzten?',
Bitte auch noch in die loginInformal.ts

2022-07-06 15:08 UTC, Franjoo commented on src/resources/scripts/i18n/de/login.ts
> +		'Durch das Zurücksetzten des Passworts kann der Zugriff auf Ihre Nachrichten eventuell nicht mehr gewährleistet werden.',
Dachte im Login gibts wohl keine informal strings. Hab das jetzt aber nachgezogen 👍

2022-07-06 16:43 UTC, web-mi requested changes

2022-07-06 16:43 UTC, web-mi commented on src/api/apiRocketChatSettings.ts
> +	const query = !settingsEntries
```suggestion
	const query = settingsEntries
```

2022-07-06 16:43 UTC, web-mi commented on src/api/apiRocketChatSettings.ts
> +		: '?query=' + JSON.stringify({ _id: { $in: settingsEntries } });
```suggestion
		: '';
```

2022-07-06 16:43 UTC, web-mi commented on src/api/apiRocketChatSettings.ts
> +		? ''
```suggestion
		? '?query=' + JSON.stringify({ _id: { $in: settingsEntries } })
```

2022-07-06 16:43 UTC, web-mi commented on src/api/apiRocketChatSettings.ts
> +	const query = !settingsEntries
Dann ist es leichter zu lesen ;-)

2022-07-06 16:43 UTC, web-mi commented on src/components/login/Login.tsx
> +	const getRcSettingsE2eEnabled = async () => {
Kannst du das hier in so einen globalen Context (src/globalState/state.tsx) auslagern der die Settings einmal holt die man braucht.
Also trotzdem die Query machen und wir können die dann erweitern sollten wir noch etwas anderes brauchen und der Provider liefert dann auch die Settings?
Sonst haben wir hier wieder die Logik direkt drin.

2022-07-09 17:55 UTC, web-mi approved these changes

2022-07-09 18:34 UTC, merged