feat: VIC-1249/1076 counsellor view tools entries + asker view shared tools
Onlineberatung/onlineBeratung-frontend pull request #621
Opened 2022-09-08 13:02 UTC by Soarecos

2022-09-08 14:23 UTC, adnanalicic requested changes

2022-09-08 14:23 UTC, adnanalicic commented on src/api/apiGetBudibaseTools.ts
> +export const apiGetBudibaseTools = async (
apiGetTools. let's try to avoid using budibase in code whenever possible, since we called also the whole backend as counslingTools-service

2022-09-08 14:23 UTC, adnanalicic commented on src/api/apiGetBudibaseTools.ts
> +	return fetchData({
this is will be always true

2022-09-08 14:23 UTC, adnanalicic commented on src/components/app/RouterConfig.tsx
> +const showAppointmentsMenuItem = (userData, _, sessionsData) => {
what is this?

2022-09-08 14:23 UTC, adnanalicic commented on src/components/app/RouterConfig.tsx
> +	console.log(userHasBudibaseTools(userData.userId));
remove console log

2022-09-08 14:23 UTC, adnanalicic commented on src/components/askerInfo/AskerInfo.tsx
> +						{config.askerToolsLink && (
we spoke about this config param, but let's not forget it

2022-09-08 14:23 UTC, adnanalicic commented on src/components/askerInfo/AskerInfoTools.tsx
> +		console.log(activeSession);
remove me

2022-09-08 14:23 UTC, adnanalicic commented on src/components/askerInfo/AskerInfoTools.tsx
> +			`${config.urls.budibaseDevServer}/?userId=${askerId}`,
this is not going to go to budibase as i initial said, we have to route the request via conslingTools service

2022-09-08 14:23 UTC, adnanalicic commented on src/components/askerInfo/AskerInfoToolsOptions.tsx
> +						tool.sharedWithAdviceSeeker === true
maybe this tool.sharedWithAdviceSeeker === true can be replaced with tool.sharedWithAdviceSeeker

2022-09-08 14:23 UTC, adnanalicic commented on src/components/askerInfo/AskerInfoToolsOptions.tsx
> +					setAvailableToolsOptions(resp);
lets speak about this

2022-09-08 14:23 UTC, adnanalicic commented on src/resources/scripts/config.ts
> +		budibaseDevServer: 'https://budibase-dev.suchtberatung.digital',
remove me

2022-09-12 14:36 UTC, CarlosSoares requested changes

2022-09-12 14:36 UTC, CarlosSoares commented on src/components/app/app.tsx
> +				const ifrm = document.createElement('iframe');
Maybe create a new function to this code and protect it with a feature flag

2022-09-12 14:36 UTC, CarlosSoares commented on src/components/app/app.tsx
> +				}, 2000);
Why the 2 seconds?

2022-09-12 14:36 UTC, CarlosSoares commented on src/components/app/navigationHandler.ts
> +export const setToolsWrapperInactive = () => {
Maybe is time to improve this 😃

2022-09-12 14:36 UTC, CarlosSoares commented on src/components/askerInfo/AskerInfoTools.tsx
> +	}, []); // eslint-disable-line react-hooks/exhaustive-deps
shouldn't you add the dependencies (`[activeSession?.item?.id, setAskerId]`)?

2022-09-12 14:36 UTC, CarlosSoares commented on src/components/askerInfo/AskerInfoToolsOptions.tsx
> +	const updateTools = (
can you create a hook with all this functions or create a file for each function? 
With that we make this code much cleaner and easy to read.
And one think that is missing is the useCallback in almost everything functions

2022-09-12 14:36 UTC, CarlosSoares commented on src/resources/scripts/config.ts
> +	budibaseSSO: true, // Feature flag to enable SSO on budibase
you can't enabled this

2022-09-12 14:36 UTC, CarlosSoares commented on src/resources/scripts/config.ts
> +		apiUrl = 'https://' + apiUrl;
Are you sure of this?

2022-09-12 14:51 UTC, Soarecos commented on src/resources/scripts/config.ts
> +		apiUrl = 'https://' + apiUrl;
Yes, I already discussed with @adnanalicic and all the calls to the server could be as https :)

2022-09-12 14:51 UTC, Soarecos commented on src/components/askerInfo/AskerInfoToolsOptions.tsx
> +	const updateTools = (
Could we discuss this in a call? I may need your help to improve like you suggested

2022-09-12 14:51 UTC, Soarecos commented on src/components/app/navigationHandler.ts
> +export const setToolsWrapperInactive = () => {
Yeah it could be great to improve this, maybe we should create a task for this improvements on JIRA :)

2022-09-12 14:51 UTC, Soarecos commented on src/components/app/app.tsx
> +				}, 2000);
Because it seems to be the minimum time needed to the auth work

2022-09-12 14:56 UTC, CarlosSoares commented on src/components/app/app.tsx
> +				}, 2000);
Could this be because of your internet? So that means that if other person has a slower connection could take longer

2022-09-12 14:57 UTC, Soarecos commented on src/components/app/app.tsx
> +				}, 2000);
Yes, we can increase to 5000 as @adnanalicic already suggested :)

2022-09-13 13:54 UTC, CarlosSoares commented on src/components/app/NavigationBar.tsx
> +		userHasBudibaseTools(userData.userId).then((resp) => setHasTools(resp));
Shouldn't this be feature flagged ?

2022-09-13 13:54 UTC, CarlosSoares commented on src/components/app/app.tsx
> +	const loginBudiBase = () => {
missing the useCallback

2022-09-13 14:00 UTC, CarlosSoares approved these changes

2022-09-13 14:19 UTC, adnanalicic approved these changes

2022-09-13 14:22 UTC, merged