feat: adding the new api to retrieve the settings from the server
Onlineberatung/onlineBeratung-frontend pull request #623
Opened 2022-09-12 13:40 UTC by CarlosSoares

## Proposed Changes

  - Adding the new way of having the app settings in an api instead of having static in the config file
  - This is protected by a feature flag called **useApiClusterSettings** so if this is enabled then we use the api settings otherwise we use the settings from the config file.
  - By default even with the flag **useApiClusterSettings** enabled we still apply the defaults from the config file
  - **Breaking change**: From now on when we want to check something regarding settings we need to use the hook **useAppConfigContext** this handles all the settings.
  - The new hook is prepared to adapt to new cluster toggles, that means that we just need to add the new key to the interface called **AppConfigInterface** and that's it, if you need some default value is also needed to set the default value in the function **UseAppConfigProvider**

2022-09-12 13:47 UTC, Soarecos commented on src/globalState/context/useAppConfig.tsx
> +			console.log({ ...settings, ...finalServerSettings });
Maybe we should remove the console.log

2022-09-12 13:51 UTC, CarlosSoares commented on src/globalState/context/useAppConfig.tsx
> +			console.log({ ...settings, ...finalServerSettings });
Ups 😃 
Removed

2022-09-12 14:05 UTC, Soarecos approved these changes, later dismissed

2022-09-13 08:05 UTC, koepferd requested changes

2022-09-13 08:05 UTC, koepferd commented on src/resources/scripts/config.ts
> +	useApiClusterSettings: true, // Feature flag to enable the cluster use the cluster settings instead of the config file
@CarlosSoares, please disable per default as the current open source version does not include the k8s setup yet.

2022-09-13 08:29 UTC, CarlosSoares commented on src/resources/scripts/config.ts
> +	useApiClusterSettings: true, // Feature flag to enable the cluster use the cluster settings instead of the config file
Done

2022-09-13 08:30 UTC, koepferd approved these changes

2022-09-13 08:30 UTC, merged