Obi 605 Keyboard usage
Onlineberatung/onlineBeratung-frontend pull request #761
Opened 2022-11-18 11:44 UTC by MelanieJakobArbeit

Fixes #

## Proposed Changes

  -
  -
  -

2022-11-18 17:10 UTC, alxbenz requested changes

2022-11-18 17:10 UTC, alxbenz commented on src/components/app/NavigationBar.tsx
> +			if (document.activeElement === ref_logout.current) {
Discussion: Could we improve this section by using switch case?

2022-11-18 17:10 UTC, alxbenz commented on src/components/select/SelectDropdown.tsx
> +						}, 10); //we need this timeout because the menu is not closed when switching the focus
👍

2022-11-18 17:10 UTC, alxbenz commented on src/components/select/select.styles.scss
> +		// &:focus {
please remove if not needed anymore

2022-11-18 17:10 UTC, alxbenz commented on src/components/sessionsList/SessionsList.tsx
> +		console.log('e', e);
please remove

2022-11-21 07:32 UTC, MelanieJakobArbeit commented on src/components/app/NavigationBar.tsx
> +			if (document.activeElement === ref_logout.current) {
yes we can

2022-11-21 09:53 UTC, alxbenz submitted a review, later dismissed

2022-11-21 09:56 UTC, alxbenz commented on src/components/app/NavigationBar.tsx
> +				if (document.activeElement === ref_logout.current) {
Better. But still really complex...
You could extract the conditions into variables. But I don't think this would help that much.
Maybe move each case into a separate function?
What do you think?

2022-11-21 10:33 UTC, MelanieJakobArbeit commented on src/components/app/NavigationBar.tsx
> +				if (document.activeElement === ref_logout.current) {
Yes that could help. I'll try it out.

2022-11-22 12:08 UTC, alxbenz approved these changes

2022-11-22 12:10 UTC, merged