feat: [OBI-871] remove org message
Onlineberatung/onlineBeratung-frontend pull request #767
Opened 2022-11-21 12:58 UTC by MelanieJakobArbeit

Fixes #

## Proposed Changes

  -
  -
  -

2022-11-21 14:28 UTC, alxbenz submitted a review, later dismissed

2022-11-30 10:07 UTC, RunzelRosinchen approved these changes, later dismissed

2022-11-30 10:18 UTC, web-mi requested changes

2022-11-30 10:18 UTC, web-mi commented on src/api/apiDraftMessages.ts
>  		responseHandling: [FETCH_ERRORS.EMPTY],
Wenn im responseHandling FETCH_SUCCESS.CONTENT mitgegeben wird  dann wird automatisch das json parse gemacht.

2022-12-01 13:55 UTC, alxbenz approved these changes

2022-12-02 08:55 UTC, web-mi approved these changes

2022-12-02 08:56 UTC, merged