feat(obi-1253): add aria labels and titles to necessary items
Onlineberatung/onlineBeratung-frontend pull request #779
Opened 2022-11-28 07:46 UTC by RunzelRosinchen

## Proposed Changes

  - Add titles and aria-labels to necessary items

2022-11-29 13:01 UTC, alxbenz requested changes

2022-11-29 13:01 UTC, alxbenz commented on src/components/twoFactorAuth/TwoFactorAuth.tsx
> +						alt="QR code"
maybe move this to the translation file aswell?

2022-11-29 13:01 UTC, alxbenz commented on src/resources/i18n/de.ts
> +		'iconTitle': 'QR-Code'
This could be used for the QR Code in my other comment.

2022-11-29 13:01 UTC, alxbenz commented on src/resources/i18n/de.ts
> +				headline: 'Hier ist Platz für Ihre Anliegen.',
Should also be translated for "de.informal".

2022-11-29 13:01 UTC, alxbenz commented on src/resources/i18n/de.ts
> +		'enquiry.new': 'Sie haben eine neue Livechat Anfrage!',
Should also be translated for "de.informal".

2022-11-30 09:50 UTC, RunzelRosinchen commented on src/resources/i18n/de.ts
> +				headline: 'Hier ist Platz für Ihre Anliegen.',
I've just added the comma for the next line, which is the same for informal and formal, this one is already translated in de.informal

2022-11-30 09:50 UTC, RunzelRosinchen commented on src/resources/i18n/de.ts
> +		'enquiry.new': 'Sie haben eine neue Livechat Anfrage!',
See comment above

2022-11-30 09:55 UTC, alxbenz approved these changes

2022-11-30 10:08 UTC, merged