Obi 1046
Onlineberatung/onlineBeratung-frontend pull request #783
Opened 2022-11-30 08:51 UTC by MelanieJakobArbeit

Fixes #

## Proposed Changes

  -
  -
  -

2022-11-30 09:53 UTC, alxbenz requested changes, later dismissed

2022-11-30 09:53 UTC, alxbenz commented on src/components/passwordReset/PasswordReset.tsx
> +					{/* <span
Can we remove this comment if it is not needed anymore?

2022-12-05 07:57 UTC, RunzelRosinchen requested changes

2022-12-05 07:57 UTC, RunzelRosinchen commented on src/resources/styles/settings.scss
> +$text-high-emphesis: rgba(0, 0, 0, 0.9);
It's emphAsis ;)

2022-12-05 08:22 UTC, RunzelRosinchen approved these changes

2022-12-05 08:54 UTC, web-mi approved these changes

2022-12-05 08:55 UTC, merged