feat: refactor the agency selection
Onlineberatung/onlineBeratung-frontend pull request #861
Opened 2023-02-16 15:01 UTC by CarlosSoares

Fixes #

## Proposed Changes

  -
  -
  -

2023-02-22 08:08 UTC, SheepFromHeaven approved these changes, later dismissed

2023-02-22 08:08 UTC, SheepFromHeaven commented on src/components/radioButton/RadioButton.tsx
> +	checkedValue?: boolean;
shouldn't one of these rather be a state?

2023-02-23 08:15 UTC, CarlosSoares commented on src/components/radioButton/RadioButton.tsx
> +	checkedValue?: boolean;
Fixed

2023-02-24 11:29 UTC, SheepFromHeaven requested changes

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/components/mainTopicSelection/MainTopicSelection.tsx
> +							checked={selectedTopic === id.toString()}
I see this "toString" everywhere. Can't we move this to the "apiGetTopicsData" function?

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/containers/registration/hooks/useConsultingTypeAgencySelection.ts
> +					!acc.find(
```suggestion
					!acc.some(
```

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/containers/registration/hooks/useConsultingTypeAgencySelection.ts
> +					acc.push(consultingTypeRel);
```suggestion
					return [...acc, consultingTypeRel];
```
I would reduce array manipulation to a minimum

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/containers/registration/hooks/useAgenciesForRegistration.ts
> +		let uniqueAgencies = uniqueBy(
```suggestion
		const uniqueAgencies = uniqueBy(
```

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/containers/registration/hooks/useAgenciesForRegistration.ts
> +			uniqueAgencies = uniqueAgencies.filter(
```suggestion
			return uniqueAgencies.filter(
```

2023-02-24 11:29 UTC, SheepFromHeaven commented on src/components/registration/RegistrationForm.tsx
> +						mainTopicId={topic?.id || formAccordionData.mainTopicId}
shouldn't this be .toString to?

2023-04-04 13:05 UTC, tkuzynow approved these changes, later dismissed

2023-04-05 10:20 UTC, RunzelRosinchen approved these changes, later dismissed

2023-04-11 08:56 UTC, tkuzynow approved these changes

2023-04-11 09:00 UTC, SheepFromHeaven approved these changes

2023-04-11 09:03 UTC, merged